INSERT INTO ROOM (NAME) VALUES ('Vardagsrum');
INSERT INTO ROOM (NAME) VALUES ('Köket');
INSERT INTO ROOM (NAME) VALUES ('Badrum');
INSERT INTO ROOM (NAME) VALUES ('Sovrum');

INSERT INTO ITEM (NAME) VALUES ('Fjärrkontroll')
INSERT INTO ITEM (NAME) VALUES ('Stekpanna')
INSERT INTO ITEM (NAME) VALUES ('Tandborste')
INSERT INTO ITEM (NAME) VALUES ('Bibel')

INSERT INTO SESSION (BOOK_ID, CUSTOMER_ID, PURCHASE_DATE) VALUES ((SELECT ID FROM BOOK WHERE AUTHOR = 'Douglas Adams'), (SELECT ID FROM CUSTOMER WHERE FIRST_NAME = 'Donald'), '2019-01-07');
